### ISSUE TITLE
Stale links?  Updates.

### ISSUE THREAD

**Issue by jboero** [fpersson/halloworld-plasmoid#1]
I would love to use this but it seems to need a little updating.  For one the link in readme for the HelloWorld tutorial is 404:
https://techbase.kde.org/Development/Tutorials/Plasma5/QML2/Helloworld
Should be:
https://techbase.kde.org/Development/Tutorials/Plasma5/QML2/HelloWorld

I have gone through that too but the default build instructions aren't working on my Fedora 34 with Plasma 5.20.  Maybe I'm missing some deps?  Does this require building Plasma or plasma-framework from source?

```
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "FindKF5Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by fpersson** [comment]
Thanks for pointing out the old url. I have updated the README.md

I think you are missing "libkf5plasma-dev" (I don't know the the Fedora name) I have tested to build the code today ant it works with Kubuntu 20.10 and OpenSuse TW.

**Comment by fpersson** [comment]
closed
